/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package template;

import picocli.CommandLine;
import picocli.CommandLine.Option;

public class App implements Runnable {

  @Option(names = {"-h", "--help"})
  private boolean help;

  @Override
  public void run() {
    if (help) {
      System.out.println(getHelp());
    } else {
      System.out.println(getGreeting());
    }
  }

  public String getGreeting() {
    return "Hello, world!";
  }

  private String getHelp() {
    return "Help message";
  }

  public static void main(String[] args) {
    final var app = new App();
    final var commandLine = new CommandLine(app);
    commandLine.execute(args);
  }
}
